name: TAG_VCF
description: |
  This module tags a VCF file with the name of the mutation caller in the INFO field.
  It appends a `CALLER` tag to each variant in the VCF file and outputs a tagged VCF file.
author: BIC @ MSKCC <bicrequest@mskcc.org>
date: 2025-04-22
version: '1.0.0'
keywords:
  - VCF
  - Variant Calling
  - Annotation
  - Bioinformatics
input:
  - - meta:
      type: map
      description: |
        Groovy Map containing metadata information
        e.g. [ id:'test', normal:'normal_sample', tumor:'tumor_sample' ]
    - vcf:
      type: path
      description: Input VCF file to be tagged.
output:
  - vcf:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*_tagged.vcf":
          type: file
          description: VCF file output
          pattern: "*_tagged.vcf"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
process:
  container:
    - nf-core/ubuntu:20.04
    - https://depot.galaxyproject.org/singularity/ubuntu:20.04
  conda: conda-forge::coreutils=9.1
  labels:
    - process_single
  tags:
    - "${meta.id}_${meta.variantcaller}"
script:
  description: |
    The script processes the input VCF file by:
    1. Copying the header lines (`##`) to the output file.
    2. Adding a new INFO field definition for the `CALLER` tag.
    3. Appending the `CALLER` tag to the INFO column of each variant line.
    4. Writing the process version information to a `versions.yml` file.
